import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { getServerSession } from "next-auth";
import AuthProvider from "./utils/SessionProvider";
import { Suspense } from "react";
import Loader from "@/components/loader/Loader";

const inter = Inter({ subsets: ["latin"] });

// metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Session provider  */}
        <AuthProvider session={session}>
          <Suspense fallback={<Loader />}>
            <Navbar />
          </Suspense>

          <div className="pt-[4rem] h-screen">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
